Vagrant.configure("2") do |config|
    config.hostmanager.enabled = true 
    config.hostmanager.manage_host = true
    
  ### DB vm  ####
    config.vm.define "db" do |db|
      db.vm.box = "eurolinux-vagrant/centos-stream-9"
      db.vm.hostname = "db01"
      db.vm.network "private_network", ip: "192.168.56.15"
      db.vm.provider "virtualbox" do |vb|
       vb.memory = "600"
     end
      db.vm.provision "shell", path: "mysql.sh"  
  
    end
    
  ### Memcache vm  #### 
    config.vm.define "memc" do |memc|
      memc.vm.box = "eurolinux-vagrant/centos-stream-9"
      memc.vm.hostname = "memc"
      memc.vm.network "private_network", ip: "192.168.56.14"
      memc.vm.provider "virtualbox" do |vb|
       vb.memory = "600"
     end
      memc.vm.provision "shell", path: "memcache.sh"  
    end
    
  ### RabbitMQ vm  ####
    config.vm.define "rbmq" do |rbmq|
      rbmq.vm.box = "eurolinux-vagrant/centos-stream-9"
    rmq01.vm.hostname = "rbmq"
      rbmq.vm.network "private_network", ip: "192.168.56.16"
      rbmq.vm.provider "virtualbox" do |vb|
       vb.memory = "600"
     end
      rbmq.vm.provision "shell", path: "rabbitmq.sh"  
    end
    
  ### tomcat vm ###
     config.vm.define "app01" do |app01|
      app01.vm.box = "eurolinux-vagrant/centos-stream-9"
      app01.vm.hostname = "app01"
      app01.vm.network "private_network", ip: "192.168.56.12"
      app01.vm.provision "shell", path: "tomcat.sh"  
      app01.vm.provider "virtualbox" do |vb|
       vb.memory = "800"
     end
     end
     
    
  ### Nginx VM ###
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/jammy64"
      web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.11"
  #  web01.vm.network "public_network"
    web01.vm.provider "virtualbox" do |vb|
       vb.gui = true
       vb.memory = "800"
     end
    web01.vm.provision "shell", path: "nginx.sh"  
  end
    
  end